filename P0AE2C06 list;

 %put NOTE- ;
 %put NOTE: Help for package sas_faker, version 0.1.0, license MIT;
 %put NOTE: *** %superq(packageTitle) ***; 
 %put NOTE- Generated: 2025-07-03T07:39:58; 
 %put NOTE- Author(s): %superq(packageAuthor); 
 %put NOTE- Maintainer(s): %superq(packageMaintainer); 
 %put NOTE- ;
 %put NOTE- *** START ***;

%let ls_tmp     = %sysfunc(getoption(ls));         
%let ps_tmp     = %sysfunc(getoption(ps));         
%let notes_tmp  = %sysfunc(getoption(notes));      
%let source_tmp = %sysfunc(getoption(source));     
options ls = MAX ps = MAX nonotes nosource;        
%include P0AE2C06(packagemetadata.sas) / nosource2; 

data _null_;                                                               
  if strip(symget("helpKeyword")) = " " then                               
    do until (EOF);                                                        
      infile P0AE2C06(description.sas) end = EOF;                
      input;                                                               
      if upcase(strip(_infile_)) =: "DESCRIPTION END:"   then printer = 0; 
      if printer then put "| " _infile_;                                   
      if upcase(strip(_infile_)) =: "DESCRIPTION START:" then printer = 1; 
    end;                                                                   
  else stop;                                                               
  put ; put "  Package contains: "; 
put @5 "1." @10 "macros " @21 "sas_faker ";
  length req $ 256;                                                     
  put ; put "  Required SAS Components: ";                              
  do req = 
"Base SAS Software"
 ;                                    
    put @3 "-" @5 req;                                                  
  end ;                                                                 
put " " / @3 "--------------------------------------------------------------------" / " ";
put @3 "*SAS package generated by SAS Package Framework, version `20241207`*";
put " " / @3 "--------------------------------------------------------------------";
run;                                                                      

data _null_;                                                   
  if upcase(strip(symget("helpKeyword"))) = "LICENSE" then     
    do until (EOF);                                            
      infile P0AE2C06(license.sas) end = EOF;        
      input;                                                   
      put "| " _infile_;                                       
    end;                                                       
  else stop;                                                   
run;                                                           

data WORK._%sysfunc(datetime(), hex16.)_;                      
infile cards4 dlm = "/";                                       
input @;                                                       
if 0 then output;                                              
length helpKeyword $ 64;                                       
retain helpKeyword "*";                                        
drop helpKeyword;                                              
if _N_ = 1 then helpKeyword = strip(symget("helpKeyword"));    
if FIND(_INFILE_, helpKeyword, "it") or helpKeyword = "*" then 
 do;                                                           
   input (folder order type file fileshort) (: $ 256.);        
   output;                                                     
 end;                                                          
cards4;                                                        
06_macros/06/macros/sas_faker.sas/sas_faker/'%sas_faker()'
;;;;
run;

data _null_;                                                                                              
if upcase(strip(symget("helpKeyword"))) in (" " "LICENSE") then do; stop; end;                            
if NOBS = 0 then do; 
put; put ' *> No help info found. Try %helpPackage(packageName,*) to display all.'; put; stop; 
end; 
  do until(EOFDS);                                                                                        
   set WORK._last_ end = EOFDS nobs = NOBS;                                                               
   length memberX $ 1024;                                                                                 
   memberX = cats("_",folder,".",file);                                                                   
   call execute("data _null_;                                                                          ");
   call execute('infile P0AE2C06(' || strip(memberX) || ') end = EOF;                        ');
   call execute("    printer = 0;                                                                      ");
   call execute("    do until(EOF);                                                                    ");
   call execute("      input;                                                                          ");
   call execute("      _endhelpline_ = upcase(reverse(strip(_infile_)));                               ");
   call execute("      if 18 <= lengthn(_endhelpline_) AND _endhelpline_                                  
                          =: '/*** DNE PLEH ***/' then printer = 0;                                  ");
   call execute("      if printer then put ""| "" _infile_;                                            ");
   call execute("      _starthelpline_ = upcase(strip(_infile_));                                      ");
   call execute("      if 20 <= lengthn(_starthelpline_) AND _starthelpline_                              
                          =: '/*** HELP START ***/' then printer = 1;                                ");
   call execute("    end;                                                                              ");
   call execute("  put "" "" / "" "";                                                                  ");
   call execute("  stop;                                                                               ");
   call execute("run;                                                                                  ");
   if lowcase(type) in ("data" "lazydata") then                                                           
    do;                                                                                                   
     call execute("title ""Dataset " || strip(fileshort) || " from package &packageName. "";           ");
     if exist(fileshort) then call execute("proc contents data = " || strip(fileshort) || "; run;      ");
     else call execute("data _null_; put ""| Dataset " || strip(fileshort) || " does not exist.""; run;");
     call execute("title;                                                                              ");
    end;                                                                                                  
  end; 
  stop; 
run; 
proc delete data = WORK._last_; 
run; 
data &packageContentDS. _NULL_;                                
 if "&packageContentDS." = " " then stop;                      
  infile cards4 dlm = "/";                                     
  input (folder order type file fileshort) (: $ 256.);         
  output;                                                      
cards4;                                                        
06_macros/06/macros/sas_faker.sas/sas_faker
;;;;
run;
options ls = &ls_tmp. ps = &ps_tmp. &notes_tmp. &source_tmp.; 

%put NOTE: Help for package sas_faker, version 0.1.0, license MIT;
%put NOTE- *** END ***;

/* help.sas end */
